# Generated by Django 5.2.1 on 2025-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_status',
            field=models.CharField(choices=[('looking', 'Looking for offers'), ('posting', 'Has posted announcement')], default='looking', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
