# Generated by Django 5.2.2 on 2025-06-25 05:17

import authuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_user_profile_status_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=authuser.models.user_profile_pic_path),
        ),
    ]
