# Generated by Django 5.2.1 on 2025-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='gender_preference',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male Only'), ('female', 'Female Only')], default='any', max_length=10),
        ),
    ]
