# Generated by Django 5.2.2 on 2025-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(blank=True, help_text='Compatibility score (0-100) - Optional', null=True),
        ),
    ]
