# Generated by Django 5.2.2 on 2025-06-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0008_alter_quizattempt_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
    ]
