# Generated by Django 5.2.2 on 2025-06-28 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0009_remove_quizattempt_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'announcement')},
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_announcements', through='etudiants.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
